sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qinyou5201314..
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    accessKeyId: LTAI5tEf1V3VwtDHeL9oALNe
    accessKeySecret: j8FuBqtqK4eMQ6YJCvWpg9j70rQNI7
    bucketName: webtlias21